/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    programmes: Programme;
    'blog-posts': BlogPost;
    events: Event;
    'student-stories': StudentStory;
    'team-members': TeamMember;
    'impact-stats': ImpactStat;
    redirects: Redirect;
    search: Search;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'student-stories': StudentStoriesSelect<false> | StudentStoriesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'impact-stats': ImpactStatsSelect<false> | ImpactStatsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'impact-page-settings': ImpactPageSetting;
    'where-we-work-settings': WhereWeWorkSetting;
    'finance-governance-settings': FinanceGovernanceSetting;
    'who-we-are-settings': WhoWeAreSetting;
    'events-page-settings': EventsPageSetting;
    'blog-page-settings': BlogPageSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'impact-page-settings': ImpactPageSettingsSelect<false> | ImpactPageSettingsSelect<true>;
    'where-we-work-settings': WhereWeWorkSettingsSelect<false> | WhereWeWorkSettingsSelect<true>;
    'finance-governance-settings': FinanceGovernanceSettingsSelect<false> | FinanceGovernanceSettingsSelect<true>;
    'who-we-are-settings': WhoWeAreSettingsSelect<false> | WhoWeAreSettingsSelect<true>;
    'events-page-settings': EventsPageSettingsSelect<false> | EventsPageSettingsSelect<true>;
    'blog-page-settings': BlogPageSettingsSelect<false> | BlogPageSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS user accounts. To invite someone for Google SSO: add their email here, set their role, then ask them to sign in at content.ourmoon.org.uk/admin using the "Sign in with Google" button. They do not need a password.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admins have full access. Editors can create and update content but cannot delete or manage users.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and documents. Supported formats: JPEG, PNG, WebP, GIF, SVG, PDF. Max 10 MB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive text for screen readers and SEO. Auto-generated from filename if left blank.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Educational programmes offered by OurMoon Education. Each programme should have a title, description, and key details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  /**
   * The full name of the programme.
   */
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title on create; edit manually if needed.
   */
  slug?: string | null;
  /**
   * Drafts are only visible to logged-in editors. Published items are visible to the public.
   */
  status: 'draft' | 'published';
  /**
   * Auto-set when status changes to Published. Override manually if needed.
   */
  publishedDate?: string | null;
  /**
   * A short summary shown on listing pages and cards. Maximum 300 characters.
   */
  shortDescription?: string | null;
  /**
   * Full programme description. Use headings to break up sections.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Main image shown on the programme page and listing cards.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Target age range for this programme.
   */
  ageRange?: string | null;
  /**
   * How long the programme runs.
   */
  duration?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * News, articles, and updates from OurMoon Education.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * The blog post headline.
   */
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title on create.
   */
  slug?: string | null;
  /**
   * Drafts are only visible to editors. Published posts are live on the website.
   */
  status: 'draft' | 'published';
  /**
   * Auto-set when published. Override to backdate.
   */
  publishedDate?: string | null;
  /**
   * Author name as it should appear on the post.
   */
  author?: string | null;
  /**
   * Short summary shown on listing pages and in search results. Max 300 characters.
   */
  excerpt?: string | null;
  /**
   * The full post content.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Main image shown at the top of the post and in listing cards.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Tags help readers find related content. Use lowercase, e.g. "space", "stem", "workshops".
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upcoming and past OurMoon Education events, workshops, and open days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The event name.
   */
  title: string;
  /**
   * URL-friendly identifier. Auto-generated from title on create.
   */
  slug?: string | null;
  /**
   * Drafts are only visible to editors.
   */
  status: 'draft' | 'published';
  /**
   * Auto-set when published.
   */
  publishedDate?: string | null;
  /**
   * How attendees can participate.
   */
  eventType?: ('in-person' | 'online' | 'hybrid') | null;
  /**
   * When the event starts.
   */
  startDate: string;
  /**
   * When the event ends. Leave blank for single-day events.
   */
  endDate?: string | null;
  /**
   * Display time string, e.g. "10:00 AM – 4:00 PM" or "Doors open at 6:30 PM".
   */
  time?: string | null;
  /**
   * Full event details, agenda, and what to expect.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Extended event content shown on the event detail page.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Physical venue address. Leave blank for online events.
   */
  location?: string | null;
  /**
   * Full URL to the registration or booking page.
   */
  registrationLink?: string | null;
  /**
   * Banner image for the event.
   */
  featuredImage?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Testimonials and success stories from OurMoon Education students.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-stories".
 */
export interface StudentStory {
  id: number;
  /**
   * The student's name. Use first name only or initials if the family prefers privacy.
   */
  studentName: string;
  /**
   * URL-friendly identifier. Auto-generated from student name on create.
   */
  slug?: string | null;
  /**
   * Drafts are only visible to editors.
   */
  status: 'draft' | 'published';
  /**
   * Featured stories appear on the homepage testimonials section.
   */
  featured?: boolean | null;
  /**
   * A short, impactful quote for display on the homepage. Max 200 characters.
   */
  shortQuote?: string | null;
  /**
   * The student's full story. Include their background, what they learned, and how it impacted them.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Photo of the student. Ensure you have permission to use their image.
   */
  photo?: (number | null) | Media;
  /**
   * Which programme did this student attend?
   */
  programme?: (number | null) | Programme;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Team members displayed on the Who We Are page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  /**
   * Groups the person under the correct team section.
   */
  region: 'zambia' | 'uk' | 'trustee';
  status: 'published' | 'draft';
  /**
   * Lower numbers appear first within the section.
   */
  order?: number | null;
  /**
   * Brief biography shown on the Who We Are page.
   */
  bio?: string | null;
  /**
   * Headshot photo. Square crops work best.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Key impact numbers displayed on the homepage and impact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats".
 */
export interface ImpactStat {
  id: number;
  value: string;
  label: string;
  status: 'published' | 'draft';
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage URL redirects. Use when you rename or move pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'programmes';
          value: number | Programme;
        } | null)
      | ({
          relationTo: 'blog-posts';
          value: number | BlogPost;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Search index — updated automatically when content is saved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'programmes';
        value: number | Programme;
      }
    | {
        relationTo: 'blog-posts';
        value: number | BlogPost;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * Build contact and registration forms without writing code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'student-stories';
        value: number | StudentStory;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'impact-stats';
        value: number | ImpactStat;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  shortDescription?: T;
  description?: T;
  featuredImage?: T;
  ageRange?: T;
  duration?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  author?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  eventType?: T;
  startDate?: T;
  endDate?: T;
  time?: T;
  description?: T;
  content?: T;
  location?: T;
  registrationLink?: T;
  featuredImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-stories_select".
 */
export interface StudentStoriesSelect<T extends boolean = true> {
  studentName?: T;
  slug?: T;
  status?: T;
  featured?: T;
  shortQuote?: T;
  story?: T;
  photo?: T;
  programme?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  region?: T;
  status?: T;
  order?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats_select".
 */
export interface ImpactStatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site configuration: branding, contact, navigation, homepage content and footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Organisation name shown in the browser tab and header.
   */
  siteName?: string | null;
  /**
   * Short strapline.
   */
  tagline?: string | null;
  /**
   * Main site logo. Recommended: SVG or PNG with transparent background.
   */
  logo?: (number | null) | Media;
  /**
   * Site favicon. Recommended: 32x32px or 64x64px .ico, .png, or .svg file.
   */
  favicon?: (number | null) | Media;
  /**
   * Main headline on the homepage hero section.
   */
  heroHeadline?: string | null;
  /**
   * Supporting text below the headline.
   */
  heroSubheadline?: string | null;
  /**
   * YouTube or Vimeo URL for the "Watch Our Film" button.
   */
  heroVideoUrl?: string | null;
  /**
   * Main hero image shown next to the headline.
   */
  heroImage?: (number | null) | Media;
  /**
   * Zambia classroom image shown in the "Founded in UK. Rooted in Zambia." section.
   */
  zambiaClassroomImage?: (number | null) | Media;
  /**
   * Logo mask image (e.g. logo icon) used at the bottom of the homepage and in the navigation header.
   */
  logoMaskImage?: (number | null) | Media;
  /**
   * Vision statement shown on the homepage.
   */
  visionStatement?: string | null;
  /**
   * Mission statement shown on the homepage.
   */
  missionStatement?: string | null;
  /**
   * Programme cards displayed in the "What We Do" section on the homepage.
   */
  whatWeDoCards?:
    | {
        /**
         * Lucide icon name: GraduationCap, Users, Sparkles, Heart, etc.
         */
        iconName?: string | null;
        /**
         * Tailwind background + text classes e.g. "bg-teal text-white".
         */
        iconColor?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Top navigation items. Items with children render as dropdowns.
   */
  navigation?:
    | {
        label: string;
        /**
         * Leave blank if this item only has children (dropdown header).
         */
        href?: string | null;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL for the Donate button in the navigation and footer.
   */
  donateUrl?: string | null;
  /**
   * UK Donation URL (Enthuse).
   */
  enthuseUrl?: string | null;
  /**
   * US Donation URL (GlobalGiving).
   */
  globalGivingUrl?: string | null;
  /**
   * Eurozone Donation URL (Maecenata).
   */
  maecenataUrl?: string | null;
  /**
   * Gift of Choice tiers shown on the donation pages and homepage.
   */
  giftTiers?:
    | {
        amount: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  bankTransfer?: {
    accountName?: string | null;
    sortCode?: string | null;
    accountNumber?: string | null;
    instructions?: string | null;
  };
  cheque?: {
    payeeName?: string | null;
    postalAddress?: string | null;
  };
  /**
   * Links shown in the "Explore" column of the footer. Leave empty to use the site defaults.
   */
  footerNavigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Short mission paragraph shown in the footer.
   */
  footerMission?: string | null;
  /**
   * UK registered charity number.
   */
  charityNumberUk?: string | null;
  /**
   * Zambia registered NGO number.
   */
  charityNumberZambia?: string | null;
  ukOffice?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  zambiaOffice?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Primary public contact email.
   */
  contactEmail?: string | null;
  /**
   * Primary public phone number.
   */
  phone?: string | null;
  /**
   * Postal address shown on the contact page.
   */
  address?: string | null;
  /**
   * Social media profiles shown in the footer.
   */
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Impact page — featured quote, inverted block, and annual reports.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page-settings".
 */
export interface ImpactPageSetting {
  id: number;
  /**
   * Pull quote displayed prominently on the Impact page.
   */
  featuredQuote?: string | null;
  /**
   * Name of the person being quoted.
   */
  featuredQuoteAuthor?: string | null;
  /**
   * Role or context for the quote author.
   */
  featuredQuoteRole?: string | null;
  /**
   * Heading for the dark/inverted content block.
   */
  invertedBlockHeading?: string | null;
  /**
   * Introductory paragraph for the inverted block.
   */
  invertedBlockIntro?: string | null;
  /**
   * Icon + title + description items displayed in the inverted block.
   */
  invertedBlockItems?:
    | {
        /**
         * Lucide icon name, e.g. GraduationCap, Users, Sparkles.
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Annual report downloads shown on the Impact page.
   */
  annualReports?:
    | {
        year: string;
        title: string;
        /**
         * The uploaded PDF or document file.
         */
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Where We Work page — hero, map, country descriptions, and video.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "where-we-work-settings".
 */
export interface WhereWeWorkSetting {
  id: number;
  /**
   * The hero background image.
   */
  heroImage?: (number | null) | Media;
  /**
   * Main heading in the hero section.
   */
  heroHeading?: string | null;
  /**
   * Supporting text beneath the hero heading.
   */
  heroSubheading?: string | null;
  /**
   * Google Maps embed URL for the Zambia location.
   */
  zambiaMapEmbedUrl?: string | null;
  /**
   * Description of OurMoon's work in Zambia.
   */
  zambiaDescription?: string | null;
  /**
   * Zambia office address.
   */
  zambiaAddress?: string | null;
  /**
   * Description of OurMoon's UK operations.
   */
  ukDescription?: string | null;
  /**
   * UK office address.
   */
  ukAddress?: string | null;
  /**
   * YouTube or Vimeo URL for the embedded video.
   */
  videoUrl?: string | null;
  /**
   * The video thumbnail image shown before play.
   */
  videoThumbnail?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Finance & Governance page — key figures, policy cards, and documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-governance-settings".
 */
export interface FinanceGovernanceSetting {
  id: number;
  /**
   * Headline statistics shown on the Finance & Governance page.
   */
  keyFigures?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Governance policy cards shown on the Finance & Governance page.
   */
  policyCards?:
    | {
        /**
         * Lucide icon name, e.g. Shield, FileText, CheckCircle.
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Downloadable governance and finance documents.
   */
  documents?:
    | {
        label: string;
        /**
         * The uploaded PDF or document file.
         */
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Who We Are page — founding story and values.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "who-we-are-settings".
 */
export interface WhoWeAreSetting {
  id: number;
  /**
   * Heading for the founding story section.
   */
  foundingStoryHeading?: string | null;
  /**
   * The founding story narrative.
   */
  foundingStoryText?: string | null;
  /**
   * Image shown alongside the founding story.
   */
  foundingStoryImage?: (number | null) | Media;
  /**
   * Heading for the values section.
   */
  valuesHeading?: string | null;
  /**
   * Introductory paragraph for the values section.
   */
  valuesIntro?: string | null;
  /**
   * Individual value items shown in the values section.
   */
  values?:
    | {
        /**
         * Lucide icon name, e.g. Heart, Star, Lightbulb.
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Events listing page — hero text and empty state messaging.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page-settings".
 */
export interface EventsPageSetting {
  id: number;
  /**
   * Main heading for the events listing page.
   */
  heroHeading?: string | null;
  /**
   * Supporting text beneath the hero heading.
   */
  heroSubheading?: string | null;
  /**
   * Heading shown when there are no upcoming events.
   */
  emptyStateHeading?: string | null;
  /**
   * Message shown when there are no upcoming events.
   */
  emptyStateText?: string | null;
  /**
   * Call-to-action button label for the empty state.
   */
  emptyStateCta?: string | null;
  /**
   * URL for the empty state call-to-action button.
   */
  emptyStateCtaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Blog listing page — hero text and featured post.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page-settings".
 */
export interface BlogPageSetting {
  id: number;
  /**
   * Main heading for the blog listing page.
   */
  heroHeading?: string | null;
  /**
   * Supporting text beneath the hero heading.
   */
  heroSubheading?: string | null;
  /**
   * Slug of the blog post to pin at the top of the listing. Leave blank to auto-select the latest post.
   */
  featuredPostSlug?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroVideoUrl?: T;
  heroImage?: T;
  zambiaClassroomImage?: T;
  logoMaskImage?: T;
  visionStatement?: T;
  missionStatement?: T;
  whatWeDoCards?:
    | T
    | {
        iconName?: T;
        iconColor?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  donateUrl?: T;
  enthuseUrl?: T;
  globalGivingUrl?: T;
  maecenataUrl?: T;
  giftTiers?:
    | T
    | {
        amount?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  bankTransfer?:
    | T
    | {
        accountName?: T;
        sortCode?: T;
        accountNumber?: T;
        instructions?: T;
      };
  cheque?:
    | T
    | {
        payeeName?: T;
        postalAddress?: T;
      };
  footerNavigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerMission?: T;
  charityNumberUk?: T;
  charityNumberZambia?: T;
  ukOffice?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  zambiaOffice?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  contactEmail?: T;
  phone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-page-settings_select".
 */
export interface ImpactPageSettingsSelect<T extends boolean = true> {
  featuredQuote?: T;
  featuredQuoteAuthor?: T;
  featuredQuoteRole?: T;
  invertedBlockHeading?: T;
  invertedBlockIntro?: T;
  invertedBlockItems?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  annualReports?:
    | T
    | {
        year?: T;
        title?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "where-we-work-settings_select".
 */
export interface WhereWeWorkSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroHeading?: T;
  heroSubheading?: T;
  zambiaMapEmbedUrl?: T;
  zambiaDescription?: T;
  zambiaAddress?: T;
  ukDescription?: T;
  ukAddress?: T;
  videoUrl?: T;
  videoThumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-governance-settings_select".
 */
export interface FinanceGovernanceSettingsSelect<T extends boolean = true> {
  keyFigures?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  policyCards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "who-we-are-settings_select".
 */
export interface WhoWeAreSettingsSelect<T extends boolean = true> {
  foundingStoryHeading?: T;
  foundingStoryText?: T;
  foundingStoryImage?: T;
  valuesHeading?: T;
  valuesIntro?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page-settings_select".
 */
export interface EventsPageSettingsSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  emptyStateHeading?: T;
  emptyStateText?: T;
  emptyStateCta?: T;
  emptyStateCtaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page-settings_select".
 */
export interface BlogPageSettingsSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  featuredPostSlug?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}